<?xml version="1.0" encoding="utf-8" ?>
<CFX>
    <HEAD>
        <VER>1.0</VER>
        <SRC></SRC>
        <DES></DES>
        <APP>${app}</APP>
        <MsgNo>${msgNo}</MsgNo>
        <MsgID>${msgID}</MsgID>
        <MsgRef>${msgRef}</MsgRef>
        <WorkDate>${workDate}</WorkDate>
        <Reserve></Reserve>
    </HEAD>
    <MSG>
        <SingleCheckResultHead0002>
            <EntrustDate>${entrustDate}</EntrustDate>
        </SingleCheckResultHead0002>
        <SingleCheckResultMessage0002>
            <CheckResult></CheckResult>
            <IssueOffice>此项暂不返回结果</IssueOffice>
            <Name>张三</Name>
            <ID>123123</ID>
            <Photo></Photo>
        </SingleCheckResultMessage0002>
    </MSG>
</CFX>